@KotKonnect.Api_HostAddress = http://localhost:5218

POST http://localhost:5218/api/auth/register
Content-Type: application/json

{
  "email": "test@etu.be",
  "motDePasse": "Test1234!",
  "role": "ETUDIANT",
  "nom": "Test",
  "prenom": "Etudiant"
}
###
